### ISSUE TITLE
Improve error handling

### ISSUE THREAD

**Issue by humphd** [AndreWillomitzer/textToHTML_V2#4]
At various places in your code, you have error paths, eg, https://github.com/AndreWillomitzer/textToHTML_V2/blob/main/textToHTML.js#L40.

Throwing an error to a user doesn't make sense: they will get a cryptic error message and a call stack.  A better approach is to give a helpful message that is *actionable*: give them an idea about how to fix things.  Then, exit the program with an error code:

```js
if(err) {
  console.error('Helpful error message here...');
  process.exit(-1);
}
```

**Comment by AndreWillomitzer** [comment]
I have added some console.log messages rather than "throw error" and I added process.exitCode = -1 to my error catches so when the program ends with an error it prints "exiting with exit code -1" after the error messages.
